export * from './TopRatedPages/TopRatedPages'
export * from './MoviesPage/MoviesPage'
export * from './MoviePage/MoviePage'
export * from './GenrePage/GenrePage'
export * from './NotFoundPage/NotFoundPage'